Entity/Computador.php
<?php

namespace Swpb\Bundle\CocarBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\UniqueConstraint;

/**
 * Printer
 *
 * @ORM\Table("tb_computador", uniqueConstraints={@UniqueConstraint(name="mac_address_idx", columns={"mac_address"})})
 * @ORM\Entity(repositoryClass="Swpb\Bundle\CocarBundle\Entity\ComputadorRepository")
 */
class Computador
{
    /**
     * Construct
     */
    public function __construct()
    {
        $this->pingComputador = new ArrayCollection();
    }

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="PingComputador", mappedBy="computador")
     */
    protected $pingComputador;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="local", type="text", nullable=true)
     */
    private $local;


    /**
     * @var string
     *
     * @ORM\Column(name="host", type="string", length=255, unique=true)
     */
    private $host;

    /**
     * @var string
     *
     * @ORM\Column(name="mac_address", type="text", nullable=true)
     */
    private $mac_address;

    /**
     * @var boolean
     *
     * @ORM\Column(name="active", type="boolean", nullable=true)
     */
    private $active;

    /**
     * @var string
     *
     * @ORM\Column(name="netmask", type="text", nullable=true)
     */
    private $netmask;

    /**
     * @var string
     *
     * @ORM\Column(name="so_name", type="text", nullable=true)
     */
    private $so_name;


    /**
     * @var string
     *
     * @ORM\Column(name="so_version", type="text", nullable=true)
     */
    private $so_version;

    /**
     * @var string
     *
     * @ORM\Column(name="accuracy", type="text", nullable=true)
     */
    private $accuracy;

    /**
     * @var string
     *
     * @ORM\Column(name="so_vendor", type="text", nullable=true)
     */
    private $so_vendor;

    /**
     * @var string
     *
     * @ORM\Column(name="so_os_family", type="text", nullable=true)
     */
    private $so_os_family;

    /**
     * @var string
     *
     * @ORM\Column(name="so_type", type="text", nullable=true)
     */
    private $so_type;

    /**
     * @var string
     *
     * @ORM\Column(name="so_cpe", type="text", nullable=true)
     */
    private $so_cpe;

    /**
     * @var integer
     *
     * @ORM\Column(name="cacic_id", type="integer", nullable=true)
     */
    private $cacic_id;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Printer
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set host
     *
     * @param string $host
     * @return Printer
     */
    public function setHost($host)
    {
        $this->host = $host;
    
        return $this;
    }

    /**
     * Get host
     *
     * @return string 
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Set local
     *
     * @param string $local
     * @return Printer
     */
    public function setLocal($local)
    {
        $this->local = $local;

        return $this;
    }

    /**
     * Get local
     *
     * @return string
     */
    public function getLocal()
    {
        return $this->local;
    }

    /**
     * Add printerCounter
     *
     * @param PrinterCounter $printerCounter
     * @return Entity
     */
    public function addPingComputador(PingComputador $pingComputador)
    {
        $pingComputador->setComputador($this);
        $this->pingComputador[] = $pingComputador;
    
        return $this;
    }

    /**
     * Remove printerCounter
     *
     * @param PrinterCounter $printerCounter
     */
    public function removePingComputador(PingComputador $pingComputador)
    {
        $this->pingComputador->removeElement($pingComputador);
    }

    /**
     * Get printerCounter
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPingComputador()
    {
        return $this->pingComputador;
    }

    /**
     * Active set
     *
     * @param $active
     * @return $this
     */
    public function setActive($active) {
        $this->active = $active;

        return $this;
    }

    /**
     * Active get
     *
     * @return bool
     */
    public function getActive() {
        return $this->active;
    }

    /**
     * Netmask set
     *
     * @param $netmask
     * @return $this
     */
    public function setNetmask($netmask) {
        $this->netmask = $netmask;

        return $this;
    }

    /**
     * Netmask get
     *
     * @return string
     */
    public function getNetmask() {
        return $this->netmask;
    }


    /**
     * @param $mac_address
     * @return $this
     */
    public function setMacAddress($mac_address) {
        $this->mac_address = $mac_address;

        return $this;
    }

    /**
     * @return string
     */
    public function getMacAddress() {
        return $this->mac_address;
    }

    /**
     * @param $so_name
     * @return $this
     */
    public function setSoName($so_name) {
        $this->so_name = $so_name;

        return $this;
    }

    /**
     * @return string
     */
    public function getSoName() {
        return $this->so_name;
    }

    /**
     * @param $so_version
     * @return $this
     */
    public function setSoVersion($so_version) {
        $this->so_version = $so_version;

        return $this;
    }

    /**
     * @return string
     */
    public function getSoVersion() {
        return $this->so_version;
    }

    /**
     * @param $accuracy
     * @return $this
     */
    public function setAccuracy($accuracy) {
        $this->accuracy = $accuracy;

        return $this;
    }

    /**
     * @return string
     */
    public function getAccuracy() {
        return $this->accuracy;
    }

    /**
     * @param $so_vendor
     * @return $this
     */
    public function setSoVendor($so_vendor) {
        $this->so_vendor = $so_vendor;

        return $this;
    }

    /**
     * @return string
     */
    public function getSoVendor() {
        return $this->so_vendor;
    }

    /**
     * @param $so_os_family
     * @return $this
     */
    public function setSoOsFamily($so_os_family) {
        $this->so_os_family = $so_os_family;

        return $this;
    }

    /**
     * @return string
     */
    public function getSoOsFamily() {
        return $this->so_os_family;
    }

    /**
     * @param $so_type
     * @return $this
     */
    public function setSoType($so_type) {
        $this->so_type = $so_type;

        return $this;
    }

    /**
     * @return string
     */
    public function getSoType() {
        return $this->so_type;
    }

    /**
     * @param $so_cpe
     * @return $this
     */
    public function setSoCpe($so_cpe) {
        $this->so_cpe = $so_cpe;

        return $this;
    }

    /**
     * @return string
     */
    public function getSoCpe() {
        return $this->so_cpe;
    }

    /**
     * @param $cacic_id
     * @return $this
     */
    public function setCacicId($cacic_id) {
        $this->cacic_id = $cacic_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getCacicId() {
        return $this->cacic_id;
    }

}

Controller/ComputadorController.php
<?php
/**
 * Created by PhpStorm.
 * User: eduardo
 * Date: 04/12/15
 * Time: 10:07
 */

namespace Swpb\Bundle\CocarBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;


/**
 * Printer controller.
 *
 * @Route("/computador")
 */
class ComputadorController extends Controller
{
    /**
     * Lists all computador entities.
     *
     * @Route("/", name="computador_index")
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request) {
        ini_set('memory_limit', '1024M');
        gc_enable();

        $em = $this->getDoctrine()->getManager();

        $form = $request->query->get('form');

        if($form)
        {
            $start = new \DateTime($form['startDate']);

            $end = new \DateTime($form['endDate']);
            $end->setTime('23', '59', '59');
        } else {

                $start = isset($start) ? $start : (time() - ((60*60*24)*30));
                $start = new \DateTime(date("Y-m-d", $start));
                $end   = isset($end) ? $end : time();
                $end = new \DateTime(date("Y-m-d", $end));
        }
        $data = new \DateTime();

        $ping = $em->getRepository('CocarBundle:PingComputador')->relatorioGeral($start, $end);

        return array(
            "ping" => $ping,
            "form" => $this->createCalendarForm(0, $start, $end)->createView(),
            "data" => $data,
            "start" => $start,
            "end" => $end
        );
    }

    /**
     * Creates a form to reports
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCalendarForm($id, $start, $end)
    {
        return $this->createFormBuilder()
            ->add('startDate', 'date', array('widget' => 'single_text', 'data' => $start))
            ->add('endDate', 'date', array('widget' => 'single_text', 'data' => $end))
            ->add('printer', 'hidden', array(
                'data' => $id
            ))
            ->getForm();
    }

}

Resources/views/Computador/index.html.twig
{% extends 'CocarBundle::layout.html.twig' %}

{% block main -%}
    <h2 class="general-title">{{ "Computadores Cadastrados"|trans }}</h2>
    <center>
        <ul>
            <li>
                <form action="{{ path('computador_index') }}" method="get" {{ form_enctype(form) }}>
                    {{ form_errors(form) }}
                    {{ form_widget(form.startDate) }}
                    {{ form_widget(form.endDate) }}
                    <button type="submit">{{ "Filtrar data"|trans }}</button>
                    <br>
                    {#<button type="submit" formaction="{{ path('printer_csv') }}">{{ "Gerar CSV"|trans }}</button>
                    <button type="submit" formaction="{{ path('printer_index_detalhado') }}">{{ "Relatório detalhado"|trans }}</button>
                    <button type="submit" formaction="{{ path('printer_models_index') }}" title="{{ 'Cadastrar modelos'| trans }}" formtarget="_blank" class="button">{{ 'Modelos de impressora'|trans }}</button>
                    <button type="submit" formaction="{{ path('printer_inactive_index') }}" title="{{ 'Verificar impressoras inativas'| trans }}" formtarget="_blank" class="button">{{ 'Impressoras inativas'|trans }}</button>#}
                </form>

            </li>
        </ul>
    </center>
    <br>
    <div class="row-fluid">
        <div class="span12 flat_box">
            <div class="padding_20">
                <p>{{ "Relatório gerado em"|trans }} {{ data|date }}</p>
                <br>
                <p>
                    <ul>
                        <li><b>{{ "Data Inicial"|trans }}</b>: {{ start|date("d/m/Y") }} {{ "00:00" }}</li>
                        <li><b>{{ "Data Final"|trans }}</b>: {{ end|date("d/m/Y") }} {{ "23:59" }}</li>
                    </ul>
                </p>
                <br>
                <p>Total de computadores: <b>{{ ping|length }}</b></p>
            </div>
        </div>
    </div>

    <table class="records_list">
        <thead>
            <tr>
                <th>#</th>
                <th>Último Ping</th>
                <th>Host</th>
                <th>MAC</th>
                <th>Ativo</th>
                <th>SO</th>
                <th>Versão SO</th>
                <th>% SO</th>
                <th>Vendor SO</th>
                <th>Família SO</th>
                <th>Tipo SO</th>
                <th>CPE SO</th>
                <th>Cacic</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in ping %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ entity.last_ping|date }}</td>
                <td>{{ entity[0].host }}</td>
                <td>{{ entity[0].macAddress }}</td>
                <td>{{ entity[0].active }}</td>
                <td>{{ entity[0].soName }}</td>
                <td>{{ entity[0].soVersion }}</td>
                <td>{{ entity[0].accuracy }}</td>
                <td>{{ entity[0].soVendor }}</td>
                <td>{{ entity[0].soOsFamily }}</td>
                <td>{{ entity[0].soType }}</td>
                <td>{{ entity[0].soCpe }}</td>
                {% if entity[0].cacicId %}
                    <td>
                        <a href="{{ path('cacic_computador_detalhar', {'idComputador' : entity[0].cacicId }) }}" title="{{ 'Detalhar computador'|trans }}" target="_blank">
                            <i class="icon-search"></i>
                        </a>
                    </td>
                {% else %}
                    <td></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script type="text/javascript">
        $( "#printers").submit(function( event ){

            // Stop form from submitting normally
            event.preventDefault();

            //var form = $( this );
            var postData = $(this).serializeArray();
            var formURL = $(this).attr("action");
            //var formData = new FormData($('form')[1]);
            $.ajax({
                type: "POST",
                url: formURL,
                data: postData,
                //processData: false,
                //contentType: false,
                success: function(){
                    location.reload();
                },
                error: function(){
                    location.reload();
                }
            });
        });
    </script>

{% endblock %}